parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 6
  project: "./tsconfig.json"
  tsconfigRootDir: "./"
env:
  browser: true
  es6: true
plugins:
  - "@typescript-eslint"
  - "react-hooks"
extends:
  - "standard"
  - "plugin:@typescript-eslint/recommended"
globals:
  tw: "readonly"
rules:
  semi:
    - error
    - always
  comma-dangle:
    - error
    - always-multiline
  "react-hooks/rules-of-hooks":
    - error
  "react-hooks/exhaustive-deps":
    - warn
  "@typescript-eslint/explicit-function-return-type": 0
  "@typescript-eslint/explicit-member-accessibility": 0
  "@typescript-eslint/no-unused-vars": 0
  "@typescript-eslint/no-explicit-any": 0
  "@typescript-eslint/no-non-null-assertion": 0
overrides:
  - files:
      - "**/*.tsx"
    rules:
      operator-linebreak:
        - error
        - before
        - overrides:
            "&&": "after"
            "?": "ignore"
            ":": "ignore"
